name: Deploy Preview and Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Add comment with preview URL
        run: |
          echo "🚀 Preview available at: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/"
          gh pr comment ${{ github.event.pull_request.number }} --body "🚀 Preview available at: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test -- --coverage
        continue-on-error: true

      - name: Add coverage report
        run: |
          COVERAGE=$(cat coverage/lcov-report/index.html)
          echo "Coverage report: $COVERAGE"
          gh pr comment ${{ github.event.pull_request.number }} --body "🧪 Unit Test Report: [Coverage Report](./coverage/lcov-report/index.html)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npm run test:e2e
        continue-on-error: true

      - name: Add E2E test report
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "🚨 E2E Test Report: ${{ steps.e2e-tests.outcome }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
